/// @description Insert description here
// You can write your code in this editor
randomise()
x = 68
y = 56
inst = instance_create_depth(x,y,0,obj_titleletter) //C
inst.image_index = 0
inst.col = 0
x += 24
inst = instance_create_depth(x,y,0,obj_titleletter) //o
inst.image_index = 1
inst.col = 10
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter) //m
inst.image_index = 2
inst.col = 20
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter) //p
inst.image_index = 3
inst.col = 30
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter) //o
inst.image_index = 1
inst.col = 40
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter) //s
inst.image_index = 4
inst.col = 50
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter) //e
inst.image_index = 5
inst.col = 60
x += 24
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 6
inst.col = 70
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 7
inst.col = 80
x += 24
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 8
inst.col = 90
x += 24
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 1
inst.col = 100
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 9
inst.col = 110
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 10
inst.col = 120
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 4
inst.col = 130
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 5
inst.col = 140
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 11
inst.col = 150
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 12
inst.col = 160
x += 12
inst = instance_create_depth(x,y,0,obj_titleletter)
inst.image_index = 13
inst.col = 170
audio_play_sound(bgm_title,0,1)